# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'deployReact' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for deployReact

  

  platform :ios, '9.0'
  target 'deployReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'deployReact-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for deployReact-tvOS

  target 'deployReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
